# theme.toml template for a Hugo theme
# See https://github.com/gzamboni/ztheme

name = "ztheme"
license = "MIT"
licenselink = "https://github.com/gzamboni/ztheme/blob/master/LICENSE.md"
description = "Personal blog built with Bootstrap, powered by Hugo"
homepage = "https://github.com/gzamboni/ztheme"
tags = ["blog", "minimal", "responsive"]
features = ["responsive", "syntax highlighting"]
min_version = "0.41.0"

[author]
  name = "Giovani Zamboni"
  homepage = "https://zamboni.dev/"

# If porting an existing theme
[original]
  name = "Sustain"
  homepage = "https://biomadeira.github.io/sustain/"
  repo = "https://github.com/biomadeira/sustain"
