email = "g@zamboni.dev"
github = "gzamboni"
gitlab = "gzamboni"
linkedin = "zamboni"
stackoverflow = "gzamboni"
twitter = "gzamboni"
instagram = "gzamboni"
quora = "gzamboni"
tumblr = "gzamboni"
reddit = "gzamboni"
telegram = "gzamboni"
dockerhub = "gzamboni"
medium = "gzamboni"
youtube = "gzamboni"
discord = "gzamboni"
mastodon = "gzamboni"
