[build]
  publish = "public"
  command = "make ci"

[context.production.environment]
  HUGO_VERSION = "0.92.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200